version: "3.9"

services:
  user_service:
    build:
      context: ./user_service
      dockerfile: Dockerfile
    container_name: user_service
    ports:
      - "8000:8000"
    env_file:
      - .env        # Sử dụng file .env từ thư mục gốc
    depends_on:
      - db
    volumes:
      - ./user_service:/app
    restart: always
    networks:
      - social_network

  post_service:
    build:
      context: ./post_service
      dockerfile: Dockerfile
    container_name: post_service
    ports:
      - "8001:8000"
    env_file:
      - .env        # Dùng chung .env
    depends_on:
      - db
    volumes:
      - ./post_service:/app
    restart: always
    networks:
      - social_network

  db:
    image: postgres:15
    container_name: social_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - social_network

volumes:
  postgres_data:

networks:
  social_network:
    driver: bridge
